### ISSUE TITLE
Not Modular Enough

### ISSUE THREAD

**Issue by cpeddecord** [kesne/mcface#2]
I feel like many of the libs in constants could, and probably should, be their own npm modules.

**Comment by jquatier** [comment]
Agreed, I was most interested in `space.js`. Thoughts on pulling this into a module?

**Comment by kesne** [comment]
@cpeddecord Thanks for your input! Rather than creating our own modules, I'll keep it DRY, and I'll use the `letters` module on NPM. This should just require a few more method calls as it is a sequential letter iterator, but it will be more tested.

@jquatier As for the space constant, not sure what the ideal module for that would look like. Maybe there's an existing module we could leverage?

**Comment by kesne** [comment]
@jquatier @cpeddecord @eltonjuan Good news! I had some time today to update this module. I created a package for all the lowercase english letters and published them (https://github.com/kesne/letters), and updated this module to use those. This should significantly improve the reliability.
